sudo: required
services:
  - docker

before_install:
  - docker build -t xander1248/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xander1248/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "aj-elastic-beanstalk"
  env: "Aj-elastic-beanstalk-env"
  bucket_name: "elasticbeanstalk-us-east-1-140350658370"
  bucket_path: "aj-elastic-beanstalk"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"